spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/pfm_db
    username: pfm_user
    password: pfm_password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/pfm_db
    user: pfm_user
    password: pfm_password

server:
  port: 8080
