spring:
  application:
    name: backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pfm_db}
    username: ${SPRING_DATASOURCE_USERNAME:pfm_user}
    password: ${SPRING_DATASOURCE_PASSWORD:pfm_password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: ${SPRING_FLYWAY_URL:${spring.datasource.url}}
    user: ${SPRING_FLYWAY_USER:${spring.datasource.username}}
    password: ${SPRING_FLYWAY_PASSWORD:${spring.datasource.password}}

server:
  port: 8080
